### ISSUE TITLE
Missing a variable definition

### ISSUE THREAD

**Issue by dkoung** [oKermorgant/log2plot#1]
Hello, 

The variable _LOG2PLOT_SCRIPT_PATH_ in line 176 of _logger.h_ is not defined. Thus, results in having compilation error when it is used as a standalone library.

https://github.com/oKermorgant/log2plot/blob/3ad6a042b28fc574672b65a66892cf1e37ea6fd8/include/log2plot/logger.h#L176

**Comment by oKermorgant** [comment]
Hi Daravuth, 

Thanks for the feedback, it is solved in the last commit.
