### ISSUE TITLE
unable to install the package

### ISSUE THREAD

**Issue by AbhinayNS** [oKermorgant/log2plot#2]
i am getting the following errors as attached in the images when i run make or sudo make install command in the build folder
![Screenshot from 2020-10-12 08-15-37](https://user-images.githubusercontent.com/47498924/95700275-417e6f00-0c64-11eb-8860-b03c32d50dcd.png)
![Screenshot from 2020-10-12 08-24-19](https://user-images.githubusercontent.com/47498924/95700370-7985b200-0c64-11eb-9753-41c0a0222b64.png)

**Comment by oKermorgant** [comment]
You have to compile with C++17
