### ISSUE TITLE
ERROR LOG2PLOT_WITH_VISP

### ISSUE THREAD

**Issue by melnarte** [oKermorgant/log2plot#3]
artem@ubuntu:~/log2plot/build$ cmake ..
CMake Error at CMakeLists.txt:64 (if):
  if given arguments:

    "NOT" "#define LOG2PLOT_WITH_VISP" "STREQUAL"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/artem/log2plot/build/CMakeFiles/CMakeOutput.log".

**Comment by oKermorgant** [comment]
Hi, 

I cannot reproduce the issue. Do you have ViSP installed / do you want to use it with log2plot?

**Comment by oKermorgant** [comment]
Hi, 
I could reproduce this issue while setting up a new computer. 
It is solved in https://github.com/oKermorgant/log2plot/commit/8b9244b48b864262445eb8bef1ea0339ca6d8756
